### ISSUE TITLE
More than one docker process for v2ray?

### ISSUE THREAD

**Issue by nadimaj** [YOUSIKI/docker-v2ray#1]
Please show example for creating **second** docker process for v2ray on same server. It must reference a different config file in a different location but how? Thank you!

**Comment by YOUSIKI** [comment]
Well, you can surely use different config files for different v2ray process. For example, there are two v2ray config files, named as `config1.json` and `config2.json`, both placed at `/etc/v2ray/`, then you might run the following commands:
``` bash
docker run --network=host --name=v2ray1 -d -v /etc/v2ray/config1.json:/etc/v2ray/config.json yousiki/v2ray -config=/etc/v2ray/config.json
docker run --network=host --name=v2ray2 -d -v /etc/v2ray/config2.json:/etc/v2ray/config.json yousiki/v2ray -config=/etc/v2ray/config.json
```
I didn't try it on my machine but I believe it will work.
Note that I have switched to Clash (which is similar to v2ray, both of them can provide proxy against GFW) for a long time, and this repo is not maintained currently. As I changed my docker hub password, the docker image `yousiki/v2ray` was out of date. So if you want to use this image, please consider to clone this repo and build it by yourself.
Thanks for your asking, and hope this answer can help you.

**Comment by nadimaj** [comment]
That is a perfect reply. Thank you so much. So i need to implement different named config files but in same name directory. I got it! :)

**Comment by nadimaj** [comment]
That is a perfect reply. Thank you so much. So i need to implement different named config files but in same name directory. I got it! :)
